### ISSUE TITLE
The " ~/.kittiviewerrc " file path can't find

### ISSUE THREAD

**Issue by muzi2045** [cedricxie/second_ros#1]
where to get this file "~/.kittiviewerrc "?
the code location is in second_ros.py -- line 167
`self.json_setting = Settings(str('/home/aisimba/' + ".kittiviewerrc"))`
thanks !

**Comment by cedricxie** [comment]
Hello @muzi2045 , this file is generated by the built in KITTI viewer from SECOND. Feel free to comment it out since it is not necessary.

Yuesong

**Comment by muzi2045** [comment]
:grinning: thank for your reply
