### ISSUE TITLE
Error during loading pre-trained net

### ISSUE THREAD

**Issue by zlfclzt1** [cedricxie/second_ros#3]
The second node and rosbag launched successfully.  But the pre-trained net can't be loaded. 
![screenshot from 2018-11-23 13-23-51](https://user-images.githubusercontent.com/9073031/48943291-14ffc380-ef23-11e8-9199-0ca40682ce37.png)

**Comment by zlfclzt1** [comment]
Solved it by replace pretrained model with own trained model. Perhaps the developer of SECOND has modified the structure of networks.

**Comment by indra4837** [comment]
@zlfclzt1 Could you share the trained model used? I am also facing this issue and am unable to train my own model. Really appreciate the help
